language: julia
os:
  - linux
  - osx

julia:
      - 1.0
      - nightly
after_success:
      - julia -e 'cd(Pkg.dir("StableHashes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
